import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import {
  ArrowDownLeft, ArrowRight, ArrowUpRight, Bell, BookOpen, CalendarDays, Check,
  ChevronDown, ChevronRight, Code2, Compass, Flame, GraduationCap, Heart,
  Layers3, LayoutDashboard, MessageCircle, MoreHorizontal, Palette, Search,
  Send, Settings2, Sparkles, Star, Target, Users, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "SkillSwap — Exchange skills, not money" },
      { name: "description", content: "Find people who can teach what you want to learn, and learn from each other." },
      { property: "og:title", content: "SkillSwap — Exchange skills, not money" },
      { property: "og:description", content: "Find your people. Share what you know. Learn something new." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: SkillSwap,
});

type View = "home" | "matches" | "room" | "progress" | "profile";
type Person = { name: string; initials: string; color: string; teaches: string[]; wants: string; match: number; online: boolean; city: string; level: string };

const people: Person[] = [
  { name: "Rahul Sharma", initials: "RS", color: "from-primary to-info", teaches: ["Photoshop", "UI Design"], wants: "Java", match: 98, online: true, city: "Pune, India", level: "Intermediate" },
  { name: "Sneha Patil", initials: "SP", color: "from-info to-success", teaches: ["Digital Marketing", "SEO"], wants: "JavaScript", match: 87, online: true, city: "Mumbai, India", level: "Advanced" },
  { name: "Aarav Mehta", initials: "AM", color: "from-warning to-primary", teaches: ["Photography", "Lightroom"], wants: "UI/UX Design", match: 84, online: false, city: "Bengaluru, India", level: "Beginner" },
];

const skills = [
  { name: "Java", learners: "1,240", category: "Programming", icon: Code2 },
  { name: "Python", learners: "2,430", category: "Programming", icon: Code2 },
  { name: "UI/UX Design", learners: "980", category: "Design", icon: Palette },
  { name: "Photoshop", learners: "1,540", category: "Design", icon: Layers3 },
  { name: "Digital Marketing", learners: "1,120", category: "Marketing", icon: Target },
  { name: "Public Speaking", learners: "760", category: "Business", icon: MessageCircle },
];

function SkillSwap() {
  const [view, setView] = useState<View>("home");
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All skills");
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState([
    { from: "Rahul", text: "Hey Tushar! Ready for today's Photoshop session?", time: "6:42 PM", mine: false },
    { from: "You", text: "Absolutely! Let's start with layers.", time: "6:44 PM", mine: true },
    { from: "Rahul", text: "Perfect. I'll explain layer masks today — they make non-destructive edits so much easier.", time: "6:45 PM", mine: false },
  ]);
  const [done, setDone] = useState([true, true, false, false]);
  const [notice, setNotice] = useState("");
  const [modal, setModal] = useState(false);
  const [mobileMenu, setMobileMenu] = useState(false);

  const filteredSkills = useMemo(() => skills.filter((skill) =>
    `${skill.name} ${skill.category}`.toLowerCase().includes(search.toLowerCase()) && (category === "All skills" || skill.category === category)), [search, category]);

  function notify(text: string) {
    setNotice(text);
    window.setTimeout(() => setNotice(""), 3000);
  }

  const navGroups = [
    { label: "WORKSPACE", items: [{ name: "Dashboard", icon: LayoutDashboard, view: "home" as View }, { name: "Find matches", icon: Compass, view: "matches" as View, count: "12" }, { name: "My exchanges", icon: Users, view: "room" as View }, { name: "Messages", icon: MessageCircle, view: "room" as View, count: "2" }] },
    { label: "YOUR JOURNEY", items: [{ name: "Learning progress", icon: GraduationCap, view: "progress" as View }, { name: "Explore skills", icon: Search, view: "matches" as View }] },
  ];

  return (
    <div className="min-h-screen bg-background text-foreground selection:bg-primary/30">
      <div className="pointer-events-none fixed inset-0 -z-0 overflow-hidden" aria-hidden="true">
        <div className="grid-texture absolute inset-0 opacity-[0.13]" />
        <div className="absolute -top-40 left-[35%] h-96 w-96 rounded-full bg-primary/10 blur-[120px]" />
      </div>
      <div className="relative z-10 flex min-h-screen">
        <aside className={`${mobileMenu ? "translate-x-0" : "-translate-x-full"} fixed inset-y-0 left-0 z-40 flex w-[252px] flex-col border-r border-border bg-background/95 px-4 py-5 backdrop-blur-xl transition-transform duration-300 lg:static lg:translate-x-0`}>
          <div className="flex items-center justify-between px-2 pb-8">
            <button onClick={() => setView("home")} className="flex items-center gap-2.5" aria-label="Go to SkillSwap dashboard">
              <span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground shadow-lg shadow-primary/20"><ArrowDownLeft size={19} strokeWidth={2.6} /></span>
              <span className="font-display text-[19px] font-bold">Skill<span className="text-primary">Swap</span></span>
            </button>
            <Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMobileMenu(false)} aria-label="Close menu"><X /></Button>
          </div>
          <div className="mb-7 rounded-xl border border-border bg-surface-soft p-3">
            <div className="mb-2 flex items-center justify-between"><span className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">Your profile</span><ChevronDown size={14} className="text-muted-foreground" /></div>
            <div className="flex items-center gap-2.5"><Avatar initials="TP" tone="from-primary to-info" size="size-9" /><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">Tushar Potdar</div><div className="text-xs text-muted-foreground">Free plan</div></div><MoreHorizontal size={17} className="text-muted-foreground" /></div>
          </div>
          {navGroups.map((group) => <div className="mb-7" key={group.label}>
            <p className="mb-2 px-2 text-[10px] font-semibold tracking-[0.12em] text-muted-foreground/80">{group.label}</p>
            <div className="space-y-1">{group.items.map(({ name, icon: Icon, view: target, count }) => <button key={name} onClick={() => { setView(target); setMobileMenu(false); }} className={`flex h-10 w-full items-center gap-3 rounded-lg px-3 text-left text-[13px] transition-colors ${view === target && ((name === "Dashboard" && view === "home") || (name === "Find matches" && view === "matches") || (name === "My exchanges" && view === "room") || (name === "Learning progress" && view === "progress")) ? "bg-accent text-accent-foreground" : "text-muted-foreground hover:bg-surface-soft hover:text-foreground"}`}><Icon size={17} /><span className="flex-1">{name}</span>{count && <span className="rounded-md bg-surface-raised px-1.5 py-0.5 text-[10px] text-muted-foreground">{count}</span>}</button>)}</div>
          </div>)}
          <div className="mt-auto space-y-1 border-t border-border pt-4">
            <button onClick={() => notify("Settings are coming soon.")} className="flex h-10 w-full items-center gap-3 rounded-lg px-3 text-[13px] text-muted-foreground hover:bg-surface-soft hover:text-foreground"><Settings2 size={17} />Settings</button>
            <button onClick={() => setView("profile")} className={`flex h-10 w-full items-center gap-3 rounded-lg px-3 text-[13px] ${view === "profile" ? "bg-accent text-accent-foreground" : "text-muted-foreground hover:bg-surface-soft hover:text-foreground"}`}><Users size={17} />Profile</button>
            <div className="mt-4 flex items-center gap-2 border-t border-border px-2 pt-4 text-[11px] text-muted-foreground"><span className="size-1.5 rounded-full bg-success" /> All systems operational <span className="ml-auto">v1.0</span></div>
          </div>
        </aside>

        {mobileMenu && <button className="fixed inset-0 z-30 bg-background/70 lg:hidden" onClick={() => setMobileMenu(false)} aria-label="Close navigation" />}

        <main className="min-w-0 flex-1 pb-20 lg:pb-0">
          <header className="sticky top-0 z-20 flex h-[68px] items-center justify-between border-b border-border/80 bg-background/85 px-4 backdrop-blur-xl sm:px-7 lg:px-9">
            <div className="flex min-w-0 items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMobileMenu(true)} aria-label="Open navigation"><LayoutDashboard /></Button><div className="hidden text-xs text-muted-foreground sm:block">Workspace <ChevronRight size={13} className="mx-1 inline" /></div><span className="truncate text-sm font-medium">{viewTitle(view)}</span></div>
            <div className="flex shrink-0 items-center gap-2"><span className="hidden rounded-full border border-success/20 bg-success/10 px-2.5 py-1 text-[11px] font-medium text-success md:inline-flex">7 day streak <Flame size={13} className="ml-1" /></span><Button variant="ghost" size="icon" className="relative" aria-label="Notifications" onClick={() => notify("You're all caught up!")}><Bell size={18} /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-primary" /></Button><span className="hidden h-6 w-px bg-border sm:block" /><button onClick={() => setView("profile")} aria-label="Open profile"><Avatar initials="TP" tone="from-primary to-info" size="size-8" /></button></div>
          </header>
          <div className="mx-auto max-w-[1440px] px-4 py-6 sm:px-7 sm:py-8 lg:px-9">
            {view === "home" && <Dashboard setView={setView} setModal={setModal} notify={notify} />}
            {view === "matches" && <Matches search={search} setSearch={setSearch} category={category} setCategory={setCategory} filteredSkills={filteredSkills} setView={setView} notify={notify} />}
            {view === "room" && <ExchangeRoom messages={messages} setMessages={setMessages} message={message} setMessage={setMessage} done={done} setDone={setDone} notify={notify} />}
            {view === "progress" && <Progress done={done} setDone={setDone} notify={notify} />}
            {view === "profile" && <Profile notify={notify} />}
          </div>
          <nav className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-5 border-t border-border bg-background/95 px-1 pb-[max(env(safe-area-inset-bottom),8px)] pt-2 backdrop-blur-xl lg:hidden">
            {[{ name: "Home", icon: LayoutDashboard, target: "home" as View }, { name: "Matches", icon: Compass, target: "matches" as View }, { name: "Messages", icon: MessageCircle, target: "room" as View }, { name: "Progress", icon: GraduationCap, target: "progress" as View }, { name: "Profile", icon: Users, target: "profile" as View }].map(({ name, icon: Icon, target }) => <button key={name} onClick={() => setView(target)} className={`flex min-w-0 flex-col items-center gap-1 py-1 text-[10px] ${view === target ? "text-primary" : "text-muted-foreground"}`}><Icon size={19} />{name}</button>)}
          </nav>
        </main>
      </div>
      {notice && <div role="status" className="fixed bottom-20 left-1/2 z-50 flex -translate-x-1/2 items-center gap-2 rounded-lg border border-border bg-popover px-4 py-3 text-sm shadow-xl lg:bottom-6"><Sparkles size={16} className="text-primary" />{notice}</div>}
      {modal && <ExchangeModal close={() => setModal(false)} enter={() => { setModal(false); setView("room"); }} />}
    </div>
  );
}

function viewTitle(view: View) { return ({ home: "Dashboard", matches: "Find matches", room: "My exchanges", progress: "Learning progress", profile: "Your profile" })[view]; }

function Avatar({ initials, tone, size = "size-10" }: { initials: string; tone: string; size?: string }) {
  return <span className={`grid ${size} shrink-0 place-items-center rounded-full bg-gradient-to-br ${tone} text-xs font-bold text-primary-foreground ring-1 ring-foreground/10`}>{initials}</span>;
}

function SectionHeading({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) {
  return <div className="mb-6 flex items-end justify-between gap-4"><div className="min-w-0">{eyebrow && <p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-primary">{eyebrow}</p>}<h1 className="font-display text-2xl font-semibold tracking-tight sm:text-[28px]">{title}</h1>{description && <p className="mt-1.5 text-sm text-muted-foreground">{description}</p>}</div>{action}</div>;
}

function Dashboard({ setView, setModal, notify }: { setView: (view: View) => void; setModal: (open: boolean) => void; notify: (text: string) => void }) {
  return <div className="space-y-7">
    <div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4"><div className="min-w-0"><p className="mb-1 text-sm text-muted-foreground">Tuesday, October 6, 2026</p><h1 className="font-display text-2xl font-semibold tracking-tight sm:text-[30px]">Good evening, Tushar <span className="text-xl">✦</span></h1><p className="mt-1 text-sm text-muted-foreground">Ready to learn something new?</p></div><Button onClick={() => setView("matches")} className="hidden shrink-0 shadow-lg shadow-primary/15 sm:inline-flex"><Sparkles size={16} /> Find a match <ArrowRight size={15} /></Button></div>

    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[{ name: "Skill matches", value: "12", note: "+3 this week", icon: Users, iconColor: "text-primary" }, { name: "Active exchanges", value: "3", note: "1 session today", icon: MessageCircle, iconColor: "text-info" }, { name: "Learning progress", value: "72%", note: "+12% this month", icon: GraduationCap, iconColor: "text-success" }, { name: "Skills taught", value: "4", note: "Across 18 sessions", icon: BookOpen, iconColor: "text-warning" }].map(({ name, value, note, icon: Icon, iconColor }) => <div key={name} className="rounded-xl border border-border bg-card/80 p-4 transition-all hover:-translate-y-0.5 hover:border-primary/30 sm:p-5"><div className="mb-4 flex items-center justify-between"><span className="text-xs text-muted-foreground">{name}</span><Icon size={17} className={iconColor} /></div><div className="flex items-baseline gap-2"><span className="font-display text-2xl font-semibold">{value}</span><span className="text-[10px] text-success">{note}</span></div></div>)}</div>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,0.9fr)]">
      <section className="overflow-hidden rounded-xl border border-border bg-card/80">
        <div className="flex items-center justify-between border-b border-border px-5 py-4"><div><div className="flex items-center gap-2"><span className="size-1.5 rounded-full bg-success" /><p className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">Your best match</p></div><h2 className="mt-1 font-display text-lg font-semibold">Meet Rahul Sharma</h2></div><button onClick={() => notify("Rahul's profile is ready to explore.")} className="rounded-full p-2 text-muted-foreground hover:bg-surface-soft hover:text-foreground" aria-label="More match options"><MoreHorizontal size={18} /></button></div>
        <div className="relative overflow-hidden p-5 sm:p-6"><div className="pointer-events-none absolute -right-8 -top-10 size-52 rounded-full bg-primary/10 blur-3xl" /><div className="relative grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div className="flex items-center gap-3.5"><Avatar initials="RS" tone="from-info to-primary" size="size-14" /><div><div className="flex items-center gap-2"><h3 className="font-semibold">Rahul Sharma</h3><span className="rounded-full bg-success/10 px-2 py-0.5 text-[10px] text-success">Online</span></div><p className="mt-1 text-xs text-muted-foreground">UI designer · Pune, India</p><div className="mt-2 flex items-center gap-1 text-xs text-warning"><Star size={13} fill="currentColor" /> 4.9 <span className="text-muted-foreground">(12 exchanges)</span></div></div></div><div className="flex items-center gap-3 md:flex-col md:items-end"><div className="flex items-baseline gap-1"><span className="font-display text-3xl font-semibold text-primary">98</span><span className="text-sm text-primary">%</span></div><span className="text-[10px] text-muted-foreground">SKILL COMPATIBILITY</span></div></div>
          <div className="relative my-6 grid grid-cols-[1fr_auto_1fr] items-stretch gap-3 rounded-lg border border-border bg-surface-soft p-3.5 sm:p-4"><div><p className="mb-2 text-[10px] uppercase tracking-wider text-muted-foreground">You teach</p><div className="flex items-center gap-2 text-sm font-medium"><span className="grid size-7 place-items-center rounded-md bg-primary/15 text-primary"><Code2 size={15} /></span>Java</div></div><div className="grid place-items-center text-muted-foreground"><ArrowRight size={17} className="rotate-180 sm:rotate-0" /></div><div><p className="mb-2 text-[10px] uppercase tracking-wider text-muted-foreground">You learn</p><div className="flex items-center gap-2 text-sm font-medium"><span className="grid size-7 place-items-center rounded-md bg-info/15 text-info"><Palette size={15} /></span>Photoshop</div></div></div>
          <div className="relative mb-5 grid grid-cols-2 gap-x-6 gap-y-3 sm:grid-cols-4">{[{ label: "Skill match", value: 100 }, { label: "Availability", value: 90 }, { label: "Experience", value: 95 }, { label: "Goals", value: 100 }].map(({ label, value }) => <div key={label}><div className="mb-1.5 flex justify-between text-[10px]"><span className="text-muted-foreground">{label}</span><span>{value}%</span></div><div className="h-1 overflow-hidden rounded-full bg-surface-raised"><div className="progress-in h-full rounded-full bg-primary" style={{ width: `${value}%` }} /></div></div>)}</div>
          <div className="relative flex flex-wrap gap-2"><Button onClick={() => setModal(true)}><ArrowRight size={15} /> Start skill exchange</Button><Button variant="outline" onClick={() => notify("Rahul's profile is ready to explore.")}>View profile</Button></div>
        </div>
      </section>
      <section className="rounded-xl border border-border bg-card/80 p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">Up next</p><h2 className="mt-1 font-display text-lg font-semibold">Your learning plan</h2></div><span className="grid size-9 place-items-center rounded-lg bg-primary/10 text-primary"><Sparkles size={17} /></span></div><div className="mb-5 rounded-lg border border-border bg-surface-soft p-3.5"><div className="mb-3 flex items-center justify-between"><span className="text-sm font-medium">Photoshop foundations</span><span className="text-xs text-primary">72%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-surface-raised"><div className="progress-in h-full w-[72%] rounded-full bg-primary" /></div><p className="mt-2 text-[10px] text-muted-foreground">Week 2 of 4 · 8 of 12 topics</p></div><div className="space-y-3">{[{ title: "Layers & layer masks", meta: "Today · 7:00 PM", icon: Layers3 }, { title: "Color correction basics", meta: "Thu · 6:30 PM", icon: Palette }].map(({ title, meta, icon: Icon }) => <div key={title} className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-surface-raised text-muted-foreground"><Icon size={16} /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{title}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{meta}</p></div><ChevronRight size={15} className="text-muted-foreground" /></div>)}</div><Button variant="outline" className="mt-5 w-full" onClick={() => setView("progress")}>View learning plan <ArrowRight size={14} /></Button></section>
    </div>

    <section><div className="mb-4 flex items-center justify-between"><div><p className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">Handpicked for you</p><h2 className="mt-1 font-display text-lg font-semibold">People to learn with</h2></div><button onClick={() => setView("matches")} className="flex items-center gap-1 text-xs text-primary hover:text-foreground">See all <ArrowRight size={14} /></button></div><div className="grid gap-3 md:grid-cols-3">{people.map((person) => <PersonCard key={person.name} person={person} onClick={() => setModal(true)} onSave={() => notify(`${person.name} saved to your list.`)} />)}</div></section>
    <section className="relative overflow-hidden rounded-xl border border-primary/20 bg-gradient-to-r from-primary/10 via-card/80 to-info/10 p-5 sm:p-6"><div className="pointer-events-none absolute inset-0 grid-texture opacity-20" /><div className="relative flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="mb-1 flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider text-primary"><Sparkles size={13} /> A little nudge</p><h2 className="font-display text-lg font-semibold">Your Java skills could unlock 12 new exchanges.</h2><p className="mt-1 text-xs text-muted-foreground">Your next great learning partner might be one click away.</p></div><Button variant="outline" className="shrink-0" onClick={() => setView("matches")}>Explore matches <ArrowUpRight size={15} /></Button></div></section>
  </div>;
}

function PersonCard({ person, onClick, onSave }: { person: Person; onClick: () => void; onSave: () => void }) {
  return <article className="rounded-xl border border-border bg-card/75 p-4 transition-all duration-200 hover:-translate-y-0.5 hover:border-primary/30"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><Avatar initials={person.initials} tone={person.color} size="size-11" /><div><div className="flex items-center gap-1.5"><h3 className="text-sm font-semibold">{person.name}</h3>{person.online && <span className="size-1.5 rounded-full bg-success" />}</div><p className="mt-0.5 text-[10px] text-muted-foreground">{person.city}</p></div></div><div className="text-right"><span className="font-display text-lg font-semibold text-primary">{person.match}%</span><p className="text-[9px] text-muted-foreground">MATCH</p></div></div><div className="my-4 grid grid-cols-2 gap-2"><div className="rounded-lg bg-surface-soft p-2.5"><p className="mb-1.5 text-[9px] uppercase tracking-wider text-muted-foreground">Can teach</p><div className="flex flex-wrap gap-1">{person.teaches.map((skill) => <span className="rounded-md border border-border px-1.5 py-1 text-[10px]" key={skill}>{skill}</span>)}</div></div><div className="rounded-lg bg-surface-soft p-2.5"><p className="mb-1.5 text-[9px] uppercase tracking-wider text-muted-foreground">Wants to learn</p><span className="text-xs font-medium">{person.wants}</span></div></div><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{person.level} level</span><div className="flex gap-1"><Button variant="ghost" size="icon" className="size-8" onClick={onSave} aria-label={`Save ${person.name}`}><Heart size={15} /></Button><Button variant="outline" size="sm" className="h-8 px-2.5 text-[10px]" onClick={onClick}>View match <ArrowRight size={12} /></Button></div></div></article>;
}

function Matches({ search, setSearch, category, setCategory, filteredSkills, setView, notify }: { search: string; setSearch: (value: string) => void; category: string; setCategory: (value: string) => void; filteredSkills: typeof skills; setView: (view: View) => void; notify: (text: string) => void }) {
  const categories = ["All skills", "Programming", "Design", "Marketing", "Business"];
  return <div className="space-y-8"><SectionHeading eyebrow="Your next exchange is out there" title="Find your perfect skill match" description="Trade what you know for something you’ve always wanted to learn." action={<div className="hidden rounded-lg border border-border bg-card px-3 py-2 text-xs text-muted-foreground sm:flex sm:items-center sm:gap-2"><Users size={14} /> 12 people match your skills</div>} />
    <div className="flex flex-col gap-3 rounded-xl border border-border bg-card/80 p-3 sm:flex-row"><div className="flex h-11 min-w-0 flex-1 items-center gap-2.5 rounded-lg border border-input bg-surface-soft px-3"><Search size={17} className="shrink-0 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="What do you want to learn?" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground" /><kbd className="hidden rounded border border-border px-1.5 py-0.5 text-[10px] text-muted-foreground sm:inline">⌘ K</kbd></div><Button className="h-11 shrink-0" onClick={() => notify("Showing your best skill matches.")}><Search size={15} /> Find matches</Button></div>
    <div className="flex gap-2 overflow-x-auto pb-1">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`shrink-0 rounded-full border px-3.5 py-2 text-xs transition-colors ${category === item ? "border-primary/40 bg-primary/10 text-primary" : "border-border text-muted-foreground hover:bg-surface-soft hover:text-foreground"}`}>{item}</button>)}</div>
    <section><div className="mb-4 flex items-center justify-between"><div><h2 className="font-display text-lg font-semibold">People who complement your skills</h2><p className="mt-1 text-xs text-muted-foreground">Sorted by compatibility with Java and your schedule.</p></div><button onClick={() => notify("Sort options coming soon.")} className="flex items-center gap-1.5 rounded-lg border border-border px-3 py-2 text-xs text-muted-foreground">Best match <ChevronDown size={14} /></button></div><div className="grid gap-3 lg:grid-cols-2 xl:grid-cols-3">{people.filter((person) => !search || `${person.wants} ${person.teaches.join(" ")}`.toLowerCase().includes(search.toLowerCase())).map((person) => <PersonCard key={person.name} person={person} onClick={() => setView("room")} onSave={() => notify(`${person.name} saved to your list.`)} />)}</div></section>
    <section><div className="mb-4 flex items-end justify-between"><div><h2 className="font-display text-lg font-semibold">Explore skills</h2><p className="mt-1 text-xs text-muted-foreground">Discover what people in the community are learning.</p></div><span className="text-xs text-muted-foreground">{filteredSkills.length} skills</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{filteredSkills.map(({ name, learners, category: group, icon: Icon }) => <button onClick={() => { setSearch(name); notify(`Finding exchange partners for ${name}.`); }} key={name} className="group flex items-center gap-3 rounded-xl border border-border bg-card/70 p-4 text-left transition-all hover:border-primary/30 hover:bg-card"><span className="grid size-10 place-items-center rounded-lg bg-primary/10 text-primary"><Icon size={18} /></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{name}</span><span className="mt-0.5 block text-[10px] text-muted-foreground">{learners} learners · {group}</span></span><ArrowUpRight size={15} className="text-muted-foreground transition-colors group-hover:text-primary" /></button>)}</div></section>
    <section className="rounded-xl border border-border bg-card/60 p-5"><div className="mb-4 flex items-center gap-2"><Compass size={16} className="text-primary" /><h2 className="text-sm font-semibold">Popular categories</h2></div><div className="flex flex-wrap gap-2">{["Programming", "Design", "Marketing", "Business", "Languages", "Photography", "Music", "Finance"].map((item) => <button key={item} onClick={() => { setCategory(item === "Languages" || item === "Photography" || item === "Music" || item === "Finance" ? "All skills" : item); setSearch(item === "All skills" ? "" : item); }} className="rounded-full border border-border px-3 py-1.5 text-xs text-muted-foreground hover:border-primary/30 hover:text-foreground">{item}</button>)}</div></section>
  </div>;
}

function ExchangeRoom({ messages, setMessages, message, setMessage, done, setDone, notify }: { messages: { from: string; text: string; time: string; mine: boolean }[]; setMessages: (messages: { from: string; text: string; time: string; mine: boolean }[]) => void; message: string; setMessage: (value: string) => void; done: boolean[]; setDone: (done: boolean[]) => void; notify: (text: string) => void }) {
  function sendMessage() { if (!message.trim()) return; setMessages([...messages, { from: "You", text: message.trim(), time: "Now", mine: true }]); setMessage(""); }
  return <div className="space-y-6"><SectionHeading eyebrow="Your active exchange" title="Java ↔ Photoshop" description="Make today’s learning hour count." action={<span className="flex items-center gap-2 rounded-full border border-success/20 bg-success/10 px-3 py-1.5 text-[11px] text-success"><span className="size-1.5 animate-pulse rounded-full bg-success" /> Both online</span>} />
    <div className="grid min-h-[600px] gap-5 xl:grid-cols-[minmax(0,1fr)_320px]">
      <section className="flex min-h-[600px] flex-col overflow-hidden rounded-xl border border-border bg-card/80"><header className="flex items-center justify-between border-b border-border px-4 py-3.5 sm:px-5"><div className="flex items-center gap-3"><div className="flex -space-x-2"><Avatar initials="TP" tone="from-primary to-info" size="size-8" /><Avatar initials="RS" tone="from-info to-success" size="size-8" /></div><div><p className="text-sm font-semibold">Exchange chat</p><p className="text-[10px] text-muted-foreground">Private room · Photoshop session</p></div></div><Button variant="ghost" size="icon" aria-label="Chat options"><MoreHorizontal /></Button></header>
        <div className="flex flex-1 flex-col gap-5 overflow-y-auto p-4 sm:p-5">{messages.map((item, index) => <div key={`${item.time}-${index}`} className={`flex max-w-[88%] gap-2.5 ${item.mine ? "ml-auto flex-row-reverse" : ""}`}><Avatar initials={item.mine ? "TP" : "RS"} tone={item.mine ? "from-primary to-info" : "from-info to-success"} size="size-8" /><div className={item.mine ? "text-right" : ""}><div className={`mb-1 flex items-center gap-2 text-[10px] text-muted-foreground ${item.mine ? "justify-end" : ""}`}><span className="font-medium text-foreground">{item.from}</span><span>{item.time}</span></div><div className={`rounded-xl border px-3.5 py-2.5 text-left text-sm leading-relaxed ${item.mine ? "rounded-tr-sm border-primary/20 bg-primary/10" : "rounded-tl-sm border-border bg-surface-soft"}`}>{item.text}</div></div></div>)}<div className="mx-auto mt-2 rounded-full border border-border bg-surface-soft px-3 py-1.5 text-[10px] text-muted-foreground">Today · October 6</div></div>
        <form onSubmit={(event) => { event.preventDefault(); sendMessage(); }} className="border-t border-border p-3 sm:p-4"><div className="flex items-end gap-2 rounded-xl border border-input bg-surface-soft p-2"><textarea value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); sendMessage(); } }} placeholder="Type a message..." rows={1} className="max-h-24 min-h-9 flex-1 resize-none bg-transparent px-2 py-2 text-sm outline-none placeholder:text-muted-foreground" /><Button size="icon" className="size-9 shrink-0" type="submit" aria-label="Send message"><Send size={15} /></Button></div><p className="mt-2 hidden px-1 text-[9px] text-muted-foreground sm:block">Press Enter to send · Shift + Enter for a new line</p></form>
      </section>
      <aside className="space-y-4"><section className="rounded-xl border border-border bg-card/80 p-4"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-sm font-semibold">Exchange overview</h2><Button variant="ghost" size="icon" className="size-8" aria-label="Exchange details"><MoreHorizontal size={17} /></Button></div><div className="space-y-3">{[{ label: "You teach", value: "Java", icon: Code2, color: "text-primary bg-primary/10" }, { label: "You learn", value: "Photoshop", icon: Palette, color: "text-info bg-info/10" }].map(({ label, value, icon: Icon, color }) => <div key={value} className="flex items-center gap-3 rounded-lg border border-border bg-surface-soft p-3"><span className={`grid size-9 place-items-center rounded-md ${color}`}><Icon size={17} /></span><div><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-0.5 text-sm font-medium">{value}</p></div></div>)}</div><div className="my-4 border-t border-border" /><p className="mb-3 text-[10px] font-medium uppercase tracking-wider text-muted-foreground">Current session</p><h3 className="text-sm font-medium">Photoshop Layers</h3><p className="mt-1 flex items-center gap-1.5 text-[10px] text-muted-foreground"><CalendarDays size={12} /> Today · 7:00 PM</p><div className="mt-4 flex items-center justify-between text-xs"><span className="text-muted-foreground">Session progress</span><span>{done.filter(Boolean).length} / 4 topics</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-surface-raised"><div className="progress-in h-full rounded-full bg-primary transition-all" style={{ width: `${done.filter(Boolean).length * 25}%` }} /></div><div className="mt-3 space-y-2">{["Layers & workspace", "Layer masks", "Blend modes", "Practice project"].map((topic, index) => <button onClick={() => { const next = [...done]; next[index] = !next[index]; setDone(next); }} key={topic} className="flex w-full items-center gap-2 text-left text-[11px]"><span className={`grid size-4 place-items-center rounded border ${done[index] ? "border-success bg-success text-success-foreground" : "border-border text-transparent"}`}><Check size={11} /></span><span className={done[index] ? "text-muted-foreground line-through" : ""}>{topic}</span></button>)}</div><Button variant="outline" className="mt-4 w-full" onClick={() => notify("Session scheduler opened.")}><CalendarDays size={14} /> Schedule session</Button></section>
        <section className="rounded-xl border border-primary/20 bg-primary/5 p-4"><div className="mb-3 flex items-center gap-2"><span className="grid size-7 place-items-center rounded-md bg-primary/15 text-primary"><Sparkles size={15} /></span><div><h2 className="text-sm font-semibold">AI Coach</h2><p className="text-[10px] text-muted-foreground">A helpful learning companion</p></div></div><div className="space-y-2"><Button variant="outline" size="sm" className="w-full justify-start text-xs" onClick={() => notify("✨ Your Photoshop learning plan is ready!")}><BookOpen size={14} /> Generate learning plan</Button><Button variant="outline" size="sm" className="w-full justify-start text-xs" onClick={() => notify("✨ Conversation summary is ready.")}><Layers3 size={14} /> Summarize conversation</Button><Button variant="outline" size="sm" className="w-full justify-start text-xs" onClick={() => notify("✨ Next up: try a non-destructive portrait retouch.")}><Sparkles size={14} /> Suggest next topic</Button></div></section></aside>
    </div>
  </div>;
}

function Progress({ done, setDone, notify }: { done: boolean[]; setDone: (done: boolean[]) => void; notify: (text: string) => void }) {
  const weeks = [{ title: "Photoshop Fundamentals", items: ["Interface & workspace", "Layers", "Selection tools"] }, { title: "Design Fundamentals", items: ["Typography", "Color theory", "Composition"] }, { title: "Practical Projects", items: ["Social media poster", "Photo editing"] }, { title: "Final Project", items: ["Portfolio design"] }];
  return <div className="space-y-7"><SectionHeading eyebrow="Small steps add up" title="Your learning progress" description="A little practice, a little progress, a lot of possibility." action={<Button onClick={() => { setDone([...done, true]); notify("Topic marked complete. Nice work!"); }}><Check size={15} /> Mark topic complete</Button>} />
    <div className="grid gap-4 xl:grid-cols-[1.35fr_0.65fr]"><section className="rounded-xl border border-border bg-card/80 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-info/10 text-info"><Palette size={20} /></span><div><p className="text-xs text-muted-foreground">Current learning path</p><h2 className="mt-0.5 font-display text-lg font-semibold">Photoshop</h2></div></div><span className="rounded-full border border-success/20 bg-success/10 px-3 py-1.5 text-xs text-success">4 week plan</span></div><div className="mt-7 flex items-end justify-between"><span className="font-display text-4xl font-semibold">72<span className="text-2xl text-primary">%</span></span><span className="text-xs text-muted-foreground">8 of 12 topics completed</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-surface-raised"><div className="progress-in h-full w-[72%] rounded-full bg-primary" /></div><div className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><Flame size={15} className="text-warning" /> You’re on a 7 day streak. Keep it going!</div></section><section className="grid grid-cols-2 gap-3">{[{ label: "Sessions completed", value: "8", icon: MessageCircle }, { label: "Hours learned", value: "12.5", icon: BookOpen }, { label: "Topics completed", value: "14", icon: Check }, { label: "Current streak", value: "7 days", icon: Flame }].map(({ label, value, icon: Icon }) => <div key={label} className="rounded-xl border border-border bg-card/75 p-4"><Icon size={16} className="mb-3 text-primary" /><p className="font-display text-xl font-semibold">{value}</p><p className="mt-1 text-[10px] text-muted-foreground">{label}</p></div>)}</section></div>
    <section><div className="mb-4 flex items-end justify-between"><div><h2 className="font-display text-lg font-semibold">Your learning plan</h2><p className="mt-1 text-xs text-muted-foreground">Photoshop journey · 4 weeks</p></div><button onClick={() => notify("✨ Your learning plan is up to date!")} className="flex items-center gap-1 text-xs text-primary"><Sparkles size={14} /> Refresh plan</button></div><div className="grid gap-3 md:grid-cols-2">{weeks.map((week, wi) => <article key={week.title} className="rounded-xl border border-border bg-card/75 p-4"><div className="mb-3 flex items-center justify-between"><div><p className="text-[10px] font-medium uppercase tracking-wider text-primary">Week {wi + 1}</p><h3 className="mt-1 text-sm font-semibold">{week.title}</h3></div><ChevronDown size={16} className="text-muted-foreground" /></div><div className="space-y-2.5">{week.items.map((topic, ti) => { const index = wi * 3 + ti; const completed = done[index] ?? index < 6; return <button key={topic} onClick={() => { const updated = [...done]; updated[index] = !completed; setDone(updated); }} className="flex w-full items-center gap-2.5 text-left text-xs"><span className={`grid size-[18px] place-items-center rounded-full border ${completed ? "border-success bg-success text-success-foreground" : "border-border text-transparent"}`}><Check size={12} /></span><span className={completed ? "text-muted-foreground line-through" : ""}>{topic}</span></button>; })}</div></article>)}</div></section>
    <section className="rounded-xl border border-border bg-card/60 p-5"><div className="mb-4 flex items-center gap-2"><Star size={16} className="text-warning" /><h2 className="font-display text-sm font-semibold">Achievements</h2></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ title: "First Skill Exchange", icon: "✦", color: "text-primary" }, { title: "7 Day Streak", icon: "🔥", color: "text-warning" }, { title: "10 Topics Completed", icon: "◎", color: "text-success" }, { title: "Great Teacher", icon: "🤝", color: "text-info" }].map(({ title, icon, color }) => <div key={title} className="flex items-center gap-3 rounded-lg border border-border bg-surface-soft p-3"><span className={`grid size-9 place-items-center rounded-lg bg-surface-raised text-base ${color}`}>{icon}</span><span className="text-xs font-medium">{title}</span><Check size={14} className="ml-auto text-success" /></div>)}</div></section>
  </div>;
}

function Profile({ notify }: { notify: (text: string) => void }) {
  return <div className="space-y-6"><SectionHeading eyebrow="Your corner of the community" title="Your profile" description="Show people what you love to teach and what you’re excited to learn." action={<Button variant="outline" onClick={() => notify("Profile editing is ready for you.")}><Settings2 size={15} /> Edit profile</Button>} /><section className="relative overflow-hidden rounded-xl border border-border bg-card/80"><div className="h-32 bg-gradient-to-r from-primary/20 via-info/10 to-success/10"><div className="grid-texture h-full opacity-25" /></div><div className="px-5 pb-5 sm:px-7"><div className="-mt-10 flex flex-col gap-4 sm:flex-row sm:items-end"><Avatar initials="TP" tone="from-primary to-info" size="size-20" /><div className="min-w-0 flex-1 pt-2"><h2 className="font-display text-xl font-semibold">Tushar Potdar</h2><p className="mt-1 text-sm text-muted-foreground">Software Developer & Learner</p></div><div className="flex gap-5 pb-1"><div><p className="font-display text-lg font-semibold">4.9 <Star size={14} className="inline text-warning" fill="currentColor" /></p><p className="text-[10px] text-muted-foreground">Exchange rating</p></div><div><p className="font-display text-lg font-semibold">12</p><p className="text-[10px] text-muted-foreground">Completed</p></div></div></div><p className="mt-5 max-w-2xl text-sm leading-relaxed text-muted-foreground">Passionate about technology, development and learning new skills. Always happy to share what I know and curious about what others can teach me.</p></div></section>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-border bg-card/75 p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-wider text-primary">Share your knowledge</p><h2 className="mt-1 font-display text-lg font-semibold">Skills I teach</h2></div><Code2 size={18} className="text-primary" /></div><div className="flex flex-wrap gap-2">{["Java", "C++", "Web Development"].map((skill) => <span key={skill} className="rounded-lg border border-primary/20 bg-primary/5 px-3 py-2 text-xs">{skill}</span>)}</div></section><section className="rounded-xl border border-border bg-card/75 p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-wider text-info">Keep your curiosity</p><h2 className="mt-1 font-display text-lg font-semibold">Skills I want to learn</h2></div><GraduationCap size={18} className="text-info" /></div><div className="flex flex-wrap gap-2">{["Photoshop", "UI/UX", "Digital Marketing"].map((skill) => <span key={skill} className="rounded-lg border border-info/20 bg-info/5 px-3 py-2 text-xs">{skill}</span>)}</div></section></div>
    <section className="rounded-xl border border-border bg-card/70 p-5"><div className="mb-4 flex items-center gap-2"><CalendarDays size={16} className="text-primary" /><h2 className="text-sm font-semibold">Availability</h2><button onClick={() => notify("Availability preferences saved.")} className="ml-auto text-xs text-primary">Edit</button></div><div className="flex flex-wrap gap-2"><span className="rounded-full border border-border bg-surface-soft px-3 py-1.5 text-xs">Tue · Evening</span><span className="rounded-full border border-border bg-surface-soft px-3 py-1.5 text-xs">Thu · Evening</span><span className="rounded-full border border-border bg-surface-soft px-3 py-1.5 text-xs">Sat · Afternoon</span></div></section>
  </div>;
}

function ExchangeModal({ close, enter }: { close: () => void; enter: () => void }) {
  return <div className="fixed inset-0 z-50 grid place-items-center bg-background/75 p-4 backdrop-blur-sm"><section role="dialog" aria-modal="true" aria-labelledby="match-success-title" className="relative w-full max-w-md overflow-hidden rounded-2xl border border-border bg-card p-6 text-center shadow-2xl sm:p-8"><button onClick={close} aria-label="Close" className="absolute right-4 top-4 rounded-md p-1 text-muted-foreground hover:bg-surface-soft"><X size={17} /></button><div className="pointer-events-none absolute -right-8 -top-8 size-36 rounded-full bg-primary/15 blur-3xl" /><div className="motion-float relative mx-auto mb-4 grid size-16 place-items-center rounded-2xl border border-primary/25 bg-primary/10 text-3xl">🤝</div><p className="relative mb-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-primary">A perfect match</p><h2 id="match-success-title" className="relative font-display text-2xl font-semibold">You found your exchange partner!</h2><div className="relative my-5 flex items-center justify-center gap-3"><Avatar initials="TP" tone="from-primary to-info" size="size-11" /><span className="text-primary">↔</span><Avatar initials="RS" tone="from-info to-success" size="size-11" /></div><p className="relative text-sm font-medium">Java <span className="mx-1 text-muted-foreground">↔</span> Photoshop</p><span className="relative mt-3 inline-flex rounded-full border border-success/20 bg-success/10 px-3 py-1 text-xs text-success">100% skill compatibility</span><p className="relative mx-auto mt-4 max-w-xs text-xs leading-relaxed text-muted-foreground">You teach what Rahul wants to learn. Rahul teaches what you want to learn.</p><div className="relative mt-6 grid gap-2"><Button className="w-full" onClick={enter}>Enter exchange room <ArrowRight size={15} /></Button><Button variant="ghost" onClick={close}>Maybe later</Button></div></section></div>;
}
